# Generated by Django 5.2.16 on 2026-07-29 18:47

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('memory', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem no artigo')),
                ('texto', models.TextField(verbose_name='texto')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('area', models.CharField(max_length=200, verbose_name='área')),
                ('area_slug', models.SlugField(max_length=200, verbose_name='slug da área')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='articles.article')),
            ],
            options={
                'verbose_name': 'trecho de memória',
                'verbose_name_plural': 'trechos de memória',
                'ordering': ['article_id', 'ordem'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='memorychunk_emb_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['area_slug'], name='memorychunk_area_idx')],
            },
        ),
    ]
