# Generated by Django 5.2.16 on 2026-07-29 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('memory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lei', 'Lei/norma'), ('jurisprudencia', 'Jurisprudência'), ('doutrina', 'Doutrina'), ('noticia', 'Notícia'), ('site', 'Site/artigo')], default='site', max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=400, verbose_name='título')),
                ('autor', models.CharField(blank=True, max_length=300, verbose_name='autor')),
                ('url', models.URLField(blank=True, max_length=800, verbose_name='URL')),
                ('trecho', models.TextField(blank=True, verbose_name='trecho citado')),
                ('data_pub', models.DateField(blank=True, null=True, verbose_name='data de publicação')),
                ('data_acesso', models.DateField(blank=True, null=True, verbose_name='data de acesso')),
                ('abnt', models.TextField(blank=True, verbose_name='referência ABNT')),
                ('verificada', models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'Verificada'), ('duvidosa', 'Duvidosa'), ('inexistente', 'Inexistente')], default='pendente', max_length=20, verbose_name='status')),
                ('verificada_em', models.DateTimeField(blank=True, null=True, verbose_name='verificada em')),
                ('nota_verificacao', models.TextField(blank=True, verbose_name='nota da verificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='articles.article')),
            ],
            options={
                'verbose_name': 'referência',
                'verbose_name_plural': 'referências',
                'ordering': ['article_id', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('article', 'url'), name='uniq_article_url')],
            },
        ),
    ]
