# Generated by Django 5.2.16 on 2026-07-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_contexto'),
        ('memory', '0003_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='nome')),
                ('slug', models.SlugField(max_length=300, verbose_name='slug')),
                ('tipo', models.CharField(choices=[('lei', 'Lei/norma'), ('jurisprudencia', 'Jurisprudência'), ('conceito', 'Conceito'), ('orgao', 'Órgão/instituição'), ('pessoa', 'Pessoa'), ('outro', 'Outro')], default='conceito', max_length=20, verbose_name='tipo')),
                ('area_slug', models.SlugField(max_length=200, verbose_name='slug da área')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'entidade',
                'verbose_name_plural': 'entidades',
                'ordering': ['area_slug', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho', models.TextField(blank=True, verbose_name='trecho')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='articles.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='memory.entity')),
            ],
            options={
                'verbose_name': 'menção de entidade',
                'verbose_name_plural': 'menções de entidade',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='articles',
            field=models.ManyToManyField(related_name='entities', through='memory.EntityMention', to='articles.article'),
        ),
        migrations.AddConstraint(
            model_name='entitymention',
            constraint=models.UniqueConstraint(fields=('entity', 'article'), name='uniq_entity_article'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('area_slug', 'slug'), name='uniq_area_entity'),
        ),
    ]
