# Generated by Django 5.2.16 on 2026-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_entity_entitymention_entity_articles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_slug', models.SlugField(max_length=200, verbose_name='slug da área')),
                ('termo', models.CharField(max_length=200, verbose_name='termo preferido')),
                ('variantes', models.TextField(blank=True, verbose_name='variantes (uma por linha)')),
                ('definicao', models.TextField(blank=True, verbose_name='definição')),
            ],
            options={
                'verbose_name': 'termo do glossário',
                'verbose_name_plural': 'glossário',
                'ordering': ['area_slug', 'termo'],
                'constraints': [models.UniqueConstraint(fields=('area_slug', 'termo'), name='uniq_area_termo')],
            },
        ),
    ]
