# Generated by Django 5.2.16 on 2026-08-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_estilo_citacao_article_perfil_layout'),
        ('memory', '0005_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='tipo',
            field=models.CharField(choices=[('lei', 'Lei/norma'), ('jurisprudencia', 'Jurisprudência'), ('doutrina', 'Doutrina'), ('noticia', 'Notícia'), ('site', 'Site/artigo'), ('video', 'Vídeo')], default='site', max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800, verbose_name='URL')),
                ('video_id', models.CharField(max_length=20, verbose_name='ID do vídeo')),
                ('titulo', models.CharField(blank=True, max_length=400, verbose_name='título')),
                ('canal', models.CharField(blank=True, max_length=300, verbose_name='canal')),
                ('publicado_em', models.CharField(blank=True, max_length=40, verbose_name='publicado em')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo')),
                ('tem_transcricao', models.BooleanField(default=False, verbose_name='tem transcrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='articles.article')),
                ('reference', models.ForeignKey(blank=True, help_text='Reference criada quando vira fonte citável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video', to='memory.reference')),
            ],
            options={
                'verbose_name': 'vídeo (fonte)',
                'verbose_name_plural': 'vídeos (fontes)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VideoIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='ideia')),
                ('citavel', models.BooleanField(default=False, verbose_name='afirmação citável')),
                ('selecionada', models.BooleanField(default=False, verbose_name='selecionada')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideias', to='memory.videosource')),
            ],
            options={
                'verbose_name': 'ideia de vídeo',
                'verbose_name_plural': 'ideias de vídeo',
                'ordering': ['video_id', 'ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='videosource',
            constraint=models.UniqueConstraint(fields=('article', 'video_id'), name='uniq_article_video'),
        ),
    ]
