# Generated by Django 5.2.16 on 2026-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_alter_reference_tipo_videosource_videoidea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='tipo',
            field=models.CharField(default='youtube', max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='url',
            field=models.URLField(blank=True, max_length=800, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='video_id',
            field=models.CharField(max_length=64, verbose_name='ID da fonte'),
        ),
    ]
