# Generated by Django 5.2.16 on 2026-07-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_contexto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucao', models.TextField(verbose_name='instrução')),
                ('secao_index', models.IntegerField(blank=True, null=True, verbose_name='índice da seção')),
                ('secao_heading', models.CharField(blank=True, max_length=300, verbose_name='título da seção')),
                ('proposta', models.TextField(blank=True, verbose_name='proposta gerada')),
                ('aplicada', models.BooleanField(default=False, verbose_name='aplicada')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_turns', to='articles.article')),
            ],
            options={
                'verbose_name': 'turno de chat',
                'verbose_name_plural': 'turnos de chat',
                'ordering': ['-criado_em'],
            },
        ),
    ]
