# Generated by Django 5.2.16 on 2026-07-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_folder_article_versao_article_folder_section'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='comentário')),
                ('resolvido', models.BooleanField(default=False, verbose_name='resolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.section')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['criado_em'],
            },
        ),
    ]
