# Generated by Django 5.2.16 on 2026-07-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('assunto', models.CharField(max_length=300, verbose_name='assunto')),
                ('area', models.CharField(max_length=200, verbose_name='área')),
                ('area_slug', models.SlugField(max_length=200, verbose_name='slug da área')),
                ('assunto_slug', models.SlugField(max_length=200, verbose_name='slug do assunto')),
                ('num_paginas', models.PositiveIntegerField(default=1, verbose_name='nº de páginas')),
                ('num_linhas', models.PositiveIntegerField(default=10, verbose_name='nº de linhas')),
                ('estilo', models.CharField(choices=[('aprofundado', 'Aprofundado'), ('raso', 'Raso'), ('intelectual', 'Intelectual'), ('popular', 'Popular'), ('juridiques', 'Juridiquês'), ('tecnico_popular', 'Técnico/Popular')], default='tecnico_popular', max_length=30, verbose_name='estilo')),
                ('pasta', models.CharField(max_length=500, verbose_name='pasta física')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pesquisa', 'Pesquisa'), ('estrutura', 'Estrutura'), ('redacao', 'Redação'), ('revisao', 'Revisão'), ('final', 'Final')], default='rascunho', max_length=30, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('area_slug', 'assunto_slug'), name='uniq_area_assunto')],
            },
        ),
    ]
