# Generated by Django 5.2.16 on 2026-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contexto',
            field=models.TextField(blank=True, verbose_name='contexto/ideia'),
        ),
    ]
