# Generated by Django 5.2.16 on 2026-07-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_contexto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'pasta',
                'verbose_name_plural': 'pastas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='versao',
            field=models.PositiveIntegerField(default=1, verbose_name='versão'),
        ),
        migrations.AddField(
            model_name='article',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.folder'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('resumo', models.TextField(blank=True, verbose_name='o que cobrir')),
                ('conteudo', models.TextField(blank=True, verbose_name='conteúdo')),
                ('meta_linhas', models.PositiveIntegerField(default=0, verbose_name='meta de linhas')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('gerando', 'Gerando'), ('pronto', 'Pronto')], default='pendente', max_length=12, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='articles.article')),
            ],
            options={
                'verbose_name': 'seção',
                'verbose_name_plural': 'seções',
                'ordering': ['article_id', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('article', 'ordem'), name='uniq_article_ordem')],
            },
        ),
    ]
