# Generated by Django 5.2.16 on 2026-07-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_folder_article_versao_article_folder_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='rótulo')),
                ('markdown', models.TextField(verbose_name='markdown')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='articles.article')),
            ],
            options={
                'verbose_name': 'snapshot',
                'verbose_name_plural': 'snapshots',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('locked', models.BooleanField(default=False, verbose_name='travado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='articles.section')),
            ],
            options={
                'verbose_name': 'parágrafo',
                'verbose_name_plural': 'parágrafos',
                'ordering': ['section_id', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('section', 'ordem'), name='uniq_section_ordem')],
            },
        ),
    ]
