# Generated by Django 5.2.16 on 2026-08-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_snapshot_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='avisos_ignorados',
            field=models.JSONField(blank=True, default=list, verbose_name='avisos ignorados'),
        ),
    ]
