# Generated by Django 5.2.16 on 2026-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_paragraph_avisos_ignorados'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publico_alvo',
            field=models.CharField(blank=True, max_length=200, verbose_name='público-alvo'),
        ),
    ]
