# Generated by Django 5.2.16 on 2026-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_publico_alvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='estilo_citacao',
            field=models.CharField(default='autor_data', max_length=20, verbose_name='estilo de citação'),
        ),
        migrations.AddField(
            model_name='article',
            name='perfil_layout',
            field=models.CharField(default='abnt', max_length=20, verbose_name='perfil de layout'),
        ),
    ]
