# Generated by Django 5.2.16 on 2026-07-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('pesquisa', 'Pesquisa'), ('estrutura', 'Estrutura'), ('redacao', 'Redação'), ('revisao', 'Revisão'), ('edicao', 'Edição final'), ('verificacao', 'Verificação')], max_length=20, verbose_name='papel')),
                ('provider', models.CharField(max_length=30, verbose_name='provedor')),
                ('model', models.CharField(max_length=80, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens de saída')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='custo (USD)')),
                ('ok', models.BooleanField(default=True, verbose_name='sucesso')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='articles.article')),
            ],
            options={
                'verbose_name': 'chamada de LLM',
                'verbose_name_plural': 'chamadas de LLM',
                'ordering': ['-criado_em'],
            },
        ),
    ]
