# Generated by Django 5.2.16 on 2026-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcall',
            name='papel',
            field=models.CharField(choices=[('pesquisa', 'Pesquisa'), ('estrutura', 'Estrutura'), ('redacao', 'Redação'), ('revisao', 'Revisão'), ('edicao', 'Edição final'), ('verificacao', 'Verificação'), ('entidades', 'Extração de entidades')], max_length=20, verbose_name='papel'),
        ),
    ]
